### ISSUE TITLE
RSS-feed link

### ISSUE THREAD

**Issue by Hanser** [ppawel/openstreetmap-website#23] opened 2013-09-08 21:20 UTC
Hi,

The RSS-feed link (the symbol) is in the last line of the 'Chronicle'-bar. So it always rushes down when the next changes are finished loading. You've got to be pretty quick to 'catch' it. Maybe it's better to put the symbol in the very first line above all the changes.

Cheers,
Johannes

**Comment by ppawel** [comment] 2013-10-01 19:29
Duplicate of #20 - I will fix this, very annoying bug indeed.

**Closed as completed by ppawel** 2013-10-01 19:29 UTC
